Add portfolio mobile
diegoh40/Diego-Portfolio pull request #1
Opened 2022-04-22 12:51 UTC by diegoh40

in this branch we can find an approach to the portfolio guided by the templete#2, I did my best to make it look like the sample, flexbox was used for the design and as far as possible the resources of images, fonts and space distribution were adapted.

2022-04-22 13:56 UTC, williamrolando88 requested changes
Hi @diegoh40 , 

### Good job so far!  👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Good job with your readme file, looks professional and neat
- Nicely done with your PR title and description, those are the bases to have a clean and professional repository

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] Nice done with your commit messages, they look very professional and descriptive 👍 , but for future references please always capitalize the first letter of your commit message.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification, also you can send me a Slack message.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 13:56 UTC, williamrolando88 commented on index.html
> +        <p>Diego Hernández</p>
- [ ] According to your requirements your logo (in this case your name), has to be wrapped with an `a` tag, to looks like a link

2022-04-22 13:56 UTC, williamrolando88 commented on styles.css
> +  height: 92px;
- [ ] Please get rid of all the width and height fixed values, the essence of this exercise is to make a responsive web design, allowed to run on a mobile device as well as on a desktop computer or laptop. If you use `display: flex` with your elements, is not necessary to add any fixed width or height. This is true for ALL other fixed widths that you have along with your CSS code. Please fix this

2022-04-22 13:56 UTC, williamrolando88 commented on styles.css
> +  position: absolute;
- [ ] Please don't use position absolute unless required. Creating an absolute positioned element will mess up your responsive design

2022-04-22 13:56 UTC, williamrolando88 commented on styles.css
> +  margin: 20px;
- [ ] To achieve the proper positioning of elements, please use `padding`, `margins` and `display: flex` associated properties like `justify-content` and `align-items`. Having a fixed position with left and top will mess up your responsive design and you're going to have a bigger headache as you keep adding features in your portfolio

2022-04-22 13:56 UTC, williamrolando88 commented on index.html
> +        <img src="./img1.png" alt="background">
- [ ] According to your requirements, this image has to be used as a CSS background, not within an `img` tag, please fix this issue

2022-04-22 13:56 UTC, williamrolando88 commented on index.html
> +        <p>Diego Hernández</p>
- [ ] According to your requirements, please use an `a` tag instead of a `p` tag

2022-04-22 13:56 UTC, williamrolando88 commented on index.html
> +        <button type="button" class="menu"> </button>
- [ ] According to your figma template, for the menu icon please use a proper icon, you could look for it in [Font Awesome](https://fontawesome.com/search?q=bars&s=solid)

2022-04-22 13:56 UTC, williamrolando88 commented on index.html
> +    </div>
- [ ] According to your requirements, for this section please use semantic tags as `section` instead of a plain `div`

2022-04-22 13:56 UTC, williamrolando88 commented on index.html
> +        <a> <img src="./smedia.png" alt="dsds"> </a>
- [ ] Please create individual elements for each one of the social media tags, the icons you can also find those icons in [Font Awesome](https://fontawesome.com/icons), create the social media icons according as the requirements says
> The list of icons uses a ul tag to group them, and li per icon; each icon has a link (a tag)

2022-04-22 13:56 UTC, williamrolando88 commented on index.html
> +        <h4>I would like you to see my some of my best works, I am able to build and design high quality websites. </h4>
- [ ] This descriptive text is it better to wrap it up in a `p` tag instead of an `h4`, remember to use `hx` tags only for headers and titles

2022-04-22 13:56 UTC, williamrolando88 commented on styles.css
> +  position: absolute;
- [ ] Please avoid using the `position` property unless is necessary, everything in this portfolio project could be made using `display: flex` and `display: grid` with the default position (unmodified)

2022-04-22 13:56 UTC, williamrolando88 commented on styles.css
> +  top: 0.1px;
- [ ] Please delete ALL the `left`, `top`, `right` and `bottom` references that you have in your document, you could use `padding` and `margin` properties instead

2022-04-22 13:56 UTC, williamrolando88 commented on styles.css
> +  position: static;
- [ ] Please avoid modifying the default `position` value unless necessary, you can create the whole portfolio only with flex-box and grid. Modifying position property will make a hell working in the responsive design in the future.

2022-04-22 13:56 UTC, williamrolando88 commented on styles.css
> +  flex-grow: 0;
- [ ] While working with flex-box is not necessary to modify the order, please keep the custom properties at a minimum while using CSS, flex-box and grid has a lot of useful default values that you don't need to be worried about

2022-04-22 13:56 UTC, williamrolando88 commented on styles.css
> +  flex-grow: 0;
- [ ] While working with flex-box is not necessary to modify the order, please keep the custom properties at a minimum while using CSS, flex-box and grid has a lot of useful default values that you don't need to be worried about

2022-04-22 22:37 UTC, diegoh40 commented
According to the suggestions I modified the header using a <a> tag, I eliminated elements that did not allow me to have a simpler and more efficient code so I eliminated elements such as (left, top.right and bottom) implemented padding and margin that are more appropriate for this exercise, I eliminated elements of type order and default position, I could add the menu button type link, in general I consider that I could implement more adequately Flexbox in the containers and item that required it, so that the page works properly in a mobile context.

2022-04-22 22:55 UTC, phelian23 requested changes
Hi @diegoh40, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 22:55 UTC, phelian23 commented on index.html
> +        <a href="#"><img src="./menu.png" alt="hamburger Icon" /></a>
- [ ] Good job working on the requested change by the previous reviewer. However, this image is not present in your repository, hence it's not loaded. Kindly add it

2022-04-22 22:55 UTC, phelian23 commented on index.html
> +            <li><img src="images/medium.png" alt="social-icon" /></li>
- [ ] Good job working on the requested change by the previous reviewer. However, this images folder is not present in your repository, hence it's not loaded. Kindly add it

2022-04-22 22:55 UTC, phelian23 commented on styles.css
> +  background-image: url('./img1.png');
- [ ] This image is not present in your repository, hence it's not loaded. Kindly add it

2022-04-22 23:29 UTC, diegoh40 commented
I have added the social networks images file and other images that I omitted in the previous commit, I will follow my reviewer's recommendations.

2022-04-23 00:27 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Diego, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!
# OPTIONAL
- [ ] Please see inline comments.
## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-23 00:27 UTC, SajjadAhmad14 commented on index.html
> +            <li><img src="images/medium.png" alt="social-icon" /></li>
[ OPTIONAL ] All the icons should be linked to your social profiles. Kindly wrap all the social images in `a` tags.

2022-04-23 01:18 UTC, diegoh40 commented
Amazing part of the project thanks for the contributions I'm going to work hard

2022-04-23 01:18 UTC, merged